//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHOADON
    {
        public string MAHD { get; set; }
        public string MAMONAN { get; set; }
        public string TENMON { get; set; }
        public int SOLUONG { get; set; }
        public bool KICHTHUOC { get; set; }
        public double GIA { get; set; }
        public double THANHTIEN { get; set; }
        public bool XOA { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual MONAN MONAN { get; set; }
    }
}
